name = "w-typing-fight"
compatibility_date = "2025-01-06"
pages_build_output_dir = "./web/dist"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"
script_name = "w-typing-fight-workers"
