name = "w-typing-fight"
compatibility_date = "2025-01-06"
pages_build_output_dir = "./web/dist"
pages_functions_dir = "./web/functions"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
