name = "w-typing-fight"
compatibility_date = "2025-01-06"
pages_build_output_dir = "dist"

# Durable Objects
[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
