/**
 * ゲーム定数
 */

export const GAME_CONSTANTS = {
  INITIAL_HP: 100,
  INITIAL_LIVES: 2,
  MAX_ROUNDS: 3, // Best of 3
  ROOM_CODE_LENGTH: 6,
  MAX_PLAYERS_PER_ROOM: 2,
} as const;

export const SCORE_ATTACK_CONSTANTS = {
  INITIAL_DURATION_MS: 60_000,
  TIME_BONUS_NO_MISS_THRESHOLD: 20,
  TIME_BONUS_MS: 1_000,
  DIFFICULTY: 'SCORE',
  DAMAGE_MULTIPLIER: 12,
} as const;
