name = "w-typing-fight-workers"
main = "src/index.ts"
compatibility_date = "2025-01-06"

# Durable Objects
[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

# Migrations for Durable Objects (SQLite required for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]
